/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* handler Class for Contact Trigger
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Kiran Kumar       <kiran.kumar@raagvitech.com>
* @modifiedBy     Kiran Kumar       <kiran.kumar@raagvitech.com>
* @maintainedBy   Kiran Kumar       <kiran.kumar@raagvitech.com>
* @version        52
* @created        2020-09-24
* @modified       
* @systemLayer    Contact Trigger Handler
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
**/
public class ContactTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert(){


    }

    public override void beforeUpdate(){


    }

    public override void beforeDelete(){


    }

    public override void afterInsert(){


    }

    public override void afterUpdate(){


    }

    public override void afterDelete(){


    }

}